################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################

baseURL = "https://davids-neighbour.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
summaryLength = 70
title = "David's Neighbour"
copyright = "All rights reserved. Copyright &copy;2020 davids-neighbour.com"
enableEmoji = false
enableGitInfo = false
enableRobotsTXT = true
disableHugoGeneratorInject = true
rssLimit = 10
pygmentsUseClasses = true
linenos = true
footnoteReturnLinkContents = "^"
