################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "https://davids-neighbour.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
# the length of text to show in a .Summary
summaryLength = 70
title = "David's Neighbour"
copyright = "All rights reserved. Copyright &copy;2020 davids-neighbour.com"
enableEmoji = false
# enable/disable functions
enableGitInfo = false # Enable GitInfo feature
enableRobotsTXT = true # Build robots.txt file
disableHugoGeneratorInject = true # Do not inject generator meta tag on homepage
rssLimit = 10
pygmentsUseClasses = true
linenos = true
footnoteReturnLinkContents = "^"
# disableKinds = ["page", "section", "RSS", "taxonomy", "taxonomyTerm", "404"]
