[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
# copyright
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"

# Dropdown menu
[[en.menu.main]]
weight = 1
name = "homepage"
hasChildren = true

[[en.menu.main]]
parent = "homepage"
name = "Homepage Full Width"
url = "homepage/full/"
weight = 1

[[en.menu.main]]
parent = "homepage"
name = "Homepage Full With Left Sidebar"
url = "homepage/full-left/"
weight = 2

[[en.menu.main]]
parent = "homepage"
name = "Homepage Full With Right Sidebar"
url = "homepage/full-right/"
weight = 3

[[en.menu.main]]
parent = "homepage"
name = "Homepage List Style"
url = "homepage/list/"
weight = 4

[[en.menu.main]]
parent = "homepage"
name = "Homepage List With Left Sidebar"
url = "homepage/list-left/"
weight = 5

[[en.menu.main]]
parent = "homepage"
name = "Homepage List With Right Sidebar"
url = "homepage/list-right/"
weight = 6


[[en.menu.main]]
name = "About"
URL = "about"
weight = 2

[[en.menu.main]]
name = "Contact"
URL = "contact"
weight = 3

# Dropdown menu
[[en.menu.main]]
weight = 4
name = "Pages"
hasChildren = true

[[en.menu.main]]
parent = "Pages"
name = "Author"
url = "author/john-doe"
weight = 1

[[en.menu.main]]
parent = "Pages"
name = "Category"
url = "categories/photography"
weight = 2

[[en.menu.main]]
parent = "Pages"
name = "Tags"
url = "tags/photo"
weight = 3

[[en.menu.main]]
parent = "Pages"
name = "Search"
url = "http://demo.themefisher.com/logbook-hugo/search/?s=image"
weight = 4


# footer menu
[[en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 2

[[en.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 3

[[en.menu.footer]]
name = "Terms Conditions"
URL = "terms-conditions"
weight = 4


