[[footer1]]
name = "@dnb-org/all"
url = "https://www.npmjs.com/package/@dnb-org/all"

[[footer1]]
name = "@dnb-org/babel-config"
url = "https://www.npmjs.com/package/@dnb-org/babel-config"

[[footer1]]
name = "@dnb-org/browserslist-config"
url = "https://www.npmjs.com/package/@dnb-org/browserslist-config"

[[footer1]]
name = "@dnb-org/bootstrap-config"
url = "https://www.npmjs.com/package/@dnb-org/bootstrap-config"

[[footer1]]
name = "@dnb-org/commitlint-config"
url = "https://www.npmjs.com/package/@dnb-org/commitlint-config"

[[footer1]]
name = "@dnb-org/cssnano-config"
url = "https://www.npmjs.com/package/@dnb-org/cssnano-config"

[[footer1]]
name = "@dnb-org/cypress-config"
url = "https://www.npmjs.com/package/@dnb-org/cypress-config"

[[footer1]]
name = "@dnb-org/eslint-config"
url = "https://www.npmjs.com/package/@dnb-org/eslint-config"

[[footer2]]
name = "@dnb-org/postcss-config"
url = "https://www.npmjs.com/package/@dnb-org/postcss-config"

[[footer2]]
name = "@dnb-org/prettier-config"
url = "https://www.npmjs.com/package/@dnb-org/prettier-config"

[[footer2]]
name = "@dnb-org/remark-config"
url = "https://www.npmjs.com/package/@dnb-org/remark-config"

[[footer2]]
name = "@dnb-org/standard-version-config"
url = "https://www.npmjs.com/package/@dnb-org/standard-version-config"

[[footer2]]
name = "@dnb-org/stylelint-config"
url = "https://www.npmjs.com/package/@dnb-org/stylelint-config"

[[footer2]]
name = "@dnb-org/textlint-config"
url = "https://www.npmjs.com/package/@dnb-org/textlint-config"

[[footer2]]
name = "@dnb-org/tools"
url = "https://www.npmjs.com/package/@dnb-org/tools"

[[footer2]]
name = "@dnb-org/webpack-config"
url = "https://www.npmjs.com/package/@dnb-org/webpack-config"

[[footer3]]
name = "Contact"
url = "/contact/"
weight = 100

[[footer3]]
name = "News"
url = "/news/"
weight = 200

[[footer3]]
name = "Notes"
url = "/notes/"
weight = 300

[[footer3]]
name = "Payment Options"
url = "/payment-options/"
weight = 340

[[footer3]]
name = "Facebook"
url = "https://facebook.com/davidsneighbour"
weight = 400

[[footer3]]
name = "Instagram"
url = "https://instagram.com/davids.neighbour"
weight = 500

[[main]]
identifier = "news"
name = "News"
url = "/news/"
weight = 310

[[main]]
identifier = "notes"
name = "Notes"
url = "/notes/"
weight = 310

[[main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 400
