[[imports]]
path = "github.com/dnb-hugo/blocks/bootstrap"
disable = false
ignoreConfig = false
ignoreImports = false

#[[imports]]
#path = "github.com/dnb-hugo/components/netlification"
#disable = false
#ignoreConfig = false
#ignoreImports = false
