[hugoVersion]
extended = false
min = "0.75.0"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-auditor"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-functions"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-netlification"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-opensearch"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-pwa"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-robots"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-security"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-sitemap"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-social"

[[imports]]
path = "github.com/dnb-org/libraries/heroicons"

[[imports]]
path = "github.com/dnb-org/shortcodes/youtube"

[[imports]]
path = "github.com/dnb-org/shortcodes/pictures"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-debug"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-hooks"
