[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/robots"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/shortcodes"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/netlification"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo-libs/bootstrap5"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo-libs/bootstrap-icons"
disabled = false
