[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/robots"

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/shortcodes"

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/netlification"

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo-libs/bootstrap5"

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo-libs/bootstrap-icons"
