[hugoVersion]
extended = false
min = "0.75.0"

[[module.imports]]
path = "github.com/tailwindlabs/heroicons"
disable = false
ignoreConfig = true
ignoreImports = true

[[module.imports.mounts]]
source = "optimized/outline"
target = "assets/icons/heroicons/outline"

[[module.imports.mounts]]
source = "optimized/solid"
target = "assets/icons/heroicons/solid"

