[[imports]]
path = "github.com/davidsneighbour/davids-neighbour.com-fonts"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/packages/robots"

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/packages/shortcodes"

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/packages/netlification"

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo-libs/bootstrap5"

[[imports]]
path="github.com/date-fns/date-fns"

[[imports.mounts]]
source="src"
target="assets/date"
