[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/favicon"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/functions"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/netlification"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/renderhooks"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/robots"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/shortcodes"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo/sitemap"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo-libs/bootstrap5"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo-libs/bootstrap-icons"
disabled = false

[[imports]]
path = "github.com/davidsneighbour/dnb-hugo-libs/popper.js"
disabled = false
