[[imports]]
path = "github.com/dnb-hugo/blocks/bootstrap"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/components/functions"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/components/netlification"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/components/pwa"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/components/renderhooks"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/components/robots"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/debugprint"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/hooks"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/shortcodes/collection"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/shortcodes/youtube"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/components/sitemap"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/libraries/bootstrap5"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/libraries/bootstrap-icons"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/libraries/popper.js"
disabled = false
