tagmanagerid = "GTM-P8XWV7K" # tagmanager container ID
version = "2018.1.159"

# social media setup
og_image = ""
og_image_url = ""
githubName = ""
twitterName =  ""

# content particles
siteslug = "davids-neighbour-de"


# opengraph internal
# see https://gohugo.io/templates/internal/#configure-open-graph
description = "Onlinemarketing Made in Paradise"
images = ["site-feature-image.jpg"]
title = "David's Neighbour"

containerMaxWidth = "700px"
dateFormat = "Jan 2, 2006"

# design elements
sitecolor = "#d02d19"

# Social networks
email = "name@domain.com"
github = "github_username"
twitter = "twitter_username"
linkedin = "linkedin_username"
facebook = "facebook_username"
google = "googleplus_id_number"
instagram = "instagram_username"
youtube = "youtube_username"
dribbble = "dribbble_username"

[social.facebook]
profileid = "517050641" # patrick.kollitsch
pageid = "6967849771" # samuisamui
appid = "2047624572136513" # samui-samui.de

[social.twitter]
profileid = "davidsneighbour"
siteid = "samui2"

# search setup
[algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[dnb]
javascript = "script-local.js"


[dnb.header]
[dnb.header.logo]
src = "/ci/logo-black-singleline.svg"
title = ""
classes = ""

[dnb.footer]
# the %s is the current year, leave out if unneeded
# everything else is parsed as markdown
copyright = "&copy; Copyright 2005-%s by [David's Neighbour Part., Ltd.](/) - All rights reserved."

[dnb.footer.menu]
title1 = "Getting Started"
title2 = "Core Concepts"
title3 = "Customization"
