---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
      #    -   id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
      #    -   id: check-shebang-scripts-are-executable
          - id: check-symlinks
          - id: check-toml
          - id: check-vcs-permalinks
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: double-quote-string-fixer
      #    -   id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending
          - id: pretty-format-json
            args: [--no-sort-keys]
          - id: sort-simple-yaml
  #    -   id: trailing-whitespace
  #        args: [--markdown-linebreak-ext=md]
  #-   repo: https://github.com/pre-commit/mirrors-csslint
  #    rev: 'v1.0.5'
  #    hooks:
  #    -   id: csslint
  #-   repo: https://github.com/pre-commit/mirrors-eslint
  #    rev: 'v7.31.0'
  #    hooks:
  #    -   id: eslint
  #        additional_dependencies:
  #        -   eslint@4.15.0
  #        -   eslint-config-google@0.7.1
  #        -   eslint-loader@1.6.1
  #        -   eslint-plugin-react@6.10.3
  #        -   babel-eslint@6.1.2
#  - repo: https://github.com/pre-commit/mirrors-scss-lint
#    rev: 'v0.59.0'  # Use the sha / tag you want to point at
#    hooks:
#      - id: scss-lint
#  - repo: https://github.com/pre-commit/mirrors-jshint
#    rev: "v2.13.0" # Use the sha / tag you want to point at
#    hooks:
#      - id: jshint
#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: "v2.3.2" # Use the sha / tag you want to point at
#    hooks:
#      - id: prettier
#-   repo: https://github.com/pre-commit/mirrors-fixmyjs
#    rev: 'v2.0.0'  # Use the sha / tag you want to point at
#    hooks:
#    -   id: fixmyjs
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.1.0
      hooks:
          - id: add-trailing-comma
#  -   repo: git://github.com/elidupuis/mirrors-sass-lint
#      sha: ''  # Use the sha you want to point at
#      hooks:
#        -   id: sass-lint
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11 # or specific tag
      hooks:
          - id: yamlfmt
fail_fast: false
minimum_pre_commit_version: 1.15.0

# https://github.com/Lucas-C/pre-commit-hooks
# https://github.com/detailyang/pre-commit-shell
# https://github.com/lovesegfault/beautysh
# https://github.com/awebdeveloper/pre-commit-stylelint
# https://github.com/jorisroovers/gitlint
# https://github.com/alessandrojcm/commitlint-pre-commit-hook
# https://github.com/milin/giticket
# https://github.com/shellcheck-py/shellcheck-py
# https://github.com/igorshubovych/markdownlint-cli
# https://github.com/markdownlint/markdownlint
# https://github.com/commitizen-tools/commitizen
# https://github.com/macisamuele/language-formatters-pre-commit-hooks
# https://github.com/pappasam/toml-sort
# https://github.com/executablebooks/mdformat
# https://github.com/editorconfig-checker/editorconfig-checker.python
# https://github.com/zricethezav/gitleaks
# https://github.com/redwarp/optimize-png-hooks
# https://github.com/kontrolilo/kontrolilo
