baseURL = "https://davids-neighbour.com/"
languageCode = "en-us"
defaultContentLanguage =      "en"
title = "David's Neighbour"
version = "1.0.10"

relativeURLs =                false
canonifyURLs =                false

enableRobotsTXT =             true
disableHugoGeneratorInject =  true
summaryLength =               70
log =                         true
logFile = "log.txt"
rssLimit =                    5
paginate =                    10
paginatePath =                "page"
stepAnalysis =                true
verbose =                     true
verboseLog =                  true
watch =                       true
