# site setup
baseURL = "https://davids-neighbour.com/" # hostname & path to the root
languageCode = "en-us"
DefaultContentLanguage = "en"

summaryLength = 70 # the length of text to show in a .Summary

# content particles
title = "David's Neighbour"
copyright = "All rights reserved. Copyright davids-neighbour.com"
enableEmoji=false

# enable/disable functions
enableGitInfo = false # Enable GitInfo feature
enableRobotsTXT = true # Build robots.txt file
disableHugoGeneratorInject = true # Do not inject generator meta tag on homepage
watch = true # watch filesystem for changes and recreate as needed

rssLimit = 10
pygmentsUseClasses = true
linenos = true

footnoteReturnLinkContents = "^"

theme = ["hugo-debugprint", "dnb-hugo-netlification", "dnb-hugo-shortcodes"]

# see http://gohugo.io/templates/output-formats/
[outputs]
home = [ "HTML", "RSS", "Algolia", "AMP" ]
page = [ "HTML", "AMP" ]
post = [ "HTML", "AMP" ]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[sitemap]
ChangeFreq = "daily"
Priority = "1"

[author]
name = "Patrick Kollitsch"
homepage = "https://davids-neighbour.com/"

# see https://gohugo.io/content-management/urls/
[permalinks]
post = "/:title/"
page = "/:title/"

[taxonomies]
tag = "tags"

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "lanczos"
# Defatult JPEG quality setting. Default is 75.
quality = 95
# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"

[[menu.main]]
name = "Startseite"
weight = 1
identifier = "posts"
url = "/"
pre = "<i class='fas fa-home fa-fw'></i>"

[[menu.main]]
name = "Archiv"
weight = 100
identifier = "archiv"
url = "/archiv/"
pre = "<i class='fas fa-archive fa-fw'></i>"

[[menu.main]]
name = "Suchen"
weight = 200
identifier = "search"
url = "/suche/"
pre = "<i class='fas fa-search fa-fw'></i>"

[[menu.main]]
name = "44"
weight = 250
identifier = "fourtyfour"
url = "https://fourtyfour.space"
pre = "<i class='fas fa-unicorn fa-fw'></i>"
target = "_blank"

[[menu.main]]
name = "DNB"
weight = 250
identifier = "dnb"
url = "https://davids-neighbour.com"
pre = "<i class='fas fa-user-tie fa-fw'></i>"
target = "_blank"

[[menu.main]]
name = "Kontakt"
weight = 300
identifier = "kontakt"
url = "/kontakt/"
pre = "<i class='fas fa-envelope fa-fw'></i>"

[related]
threshold = 80 # Only include matches with rank >= threshold. 0 and 100.
includeNewer = true # adding newer articles to older ones (changing the content)
toLower = true # Will lower case keywords in both queries and in the indexes.

[[related.indices]]
name  = "tags"
weight = 100

[[related.indices]]
name  = "date"
weight = 10
pattern = "2006" # “200601” for busier times?

[params]
tagmanagerid = "GTM-P8XWV7K" # tagmanager container ID
version = "2018.1.159"

# social media setup
og_image = ""
og_image_url = ""
githubName = ""
twitterName =  ""

# content particles
siteslug = "davids-neighbour-de"
description = "Onlinemarketing Made in Paradise"

# design elements
sitecolor = "#d02d19"

# Social networks
email = "name@domain.com"
github = "github_username"
twitter = "twitter_username"
linkedin = "linkedin_username"
facebook = "facebook_username"
google = "googleplus_id_number"
instagram = "instagram_username"
youtube = "youtube_username"
dribbble = "dribbble_username"

[params.social.facebook]
profileid = "517050641" # patrick.kollitsch
pageid = "6967849771" # samuisamui
appid = "2047624572136513" # samui-samui.de

[params.social.twitter]
profileid = "davidsneighbour"
siteid = "samui2"

# search setup
[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
