[build]
  publish = "public"
  command = "yarn install && hugo"

[context.production]
  command = "yarn install && hugo"
  [context.production.environment]
    HUGO_VERSION = "0.55.6"
    HUGO_ENV = "production"
