[build]
base = "/"
publish = "public"

[context.production]
#command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.77.0"
HUGO_ENV = "production"

[context.deploy-preview]
#command = "hugo --gc"
