[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production]
  command = "hugo --gc --minify"
  [context.production.environment]
    HUGO_VERSION = "0.57.1"
    HUGO_ENV = "production"
