[[imports]]
path = "github.com/dnb-org/blocks/bootstrap5"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/dnb-org/components/netlification"
disable = false
ignoreConfig = false
ignoreImports = false
